version: '3'

services:
  registry:
    image: registry:2.7.0
    container_name: registry
    ports:
      - "5000:5000"
    restart: on-failure
    volumes:
      - registry_volume:/var/lib/registry

volumes:
  registry_volume:
    driver: local
