version: '3'

services:
  mysql:
    image: localhost:5000/mysql
    volumes:
      - ./mysql/quotes:/docker-entrypoint-initdb.d
      - ./volumes/testdata/mysql:/testdata
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  phpmyadmin:
    image: localhost:5000/phpmyadmin
    ports:
      - "8888:80"
    links:
      - mysql
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=secret
      - PMA_HOST=mysql
    depends_on:
      - mysql

  payara:
    image: localhost:5000/back-end
    ports:
      - "8080:8080"
      - "4848:4848"
      - "8181:8181"
      - "8009:8009"
    links:
      - mysql:mysql
    depends_on:
      - mysql

#  payara:
#    image: localhost:5000/server
#    ports:
#      - "8080:8080"
#      - "4848:4848"
#      - "8181:8181"
#      - "8009:8009"
#    links:
#      - mysql:mysql
#    depends_on:
#      - mysql
#    volumes:
#      - ./back-end/artifact:/opt/payara5/glassfish/domains/domain1/autodeploy

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: localhost:5000/web
    ports:
      - "3000:3000"
    links:
      - payara
    depends_on:
      - payara

volumes:
  mysql-data:
    driver: local